// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Musica.Models;

[Table("Artist")]
public partial class Artist
{
    [Key]
    public int ArtistId { get; set; }

<<<<<<<< HEAD:Musica/Models/Artist.cs
    [StringLength(120)]
========
    [Required(ErrorMessage = "Campo olbitario.")]
    [StringLength(160, MinimumLength = 1, ErrorMessage = "Introduce un título entre 1 y 120 carácteres.")]
    [DisplayName("Nombre")]
>>>>>>>> f06e521 (Commit):IzquierdoAndres_Musica_Identity/Models/Artist.cs
    public string Name { get; set; }

    [InverseProperty("Artist")]
    public virtual ICollection<Album> Albums { get; set; } = new List<Album>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}