// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Musica.Models;

[Table("Track")]
[Index("AlbumId", Name = "IFK_TrackAlbumId")]
[Index("GenreId", Name = "IFK_TrackGenreId")]
[Index("MediaTypeId", Name = "IFK_TrackMediaTypeId")]
public partial class Track
{
    [Key]
    public int TrackId { get; set; }

    [Required(ErrorMessage = "Campo olbitario.")]
    [StringLength(200)]
    public string Name { get; set; }

    public int? AlbumId { get; set; }

    public int MediaTypeId { get; set; }

    public int? GenreId { get; set; }

    [Required(ErrorMessage = "Campo olbitario.")]
    [StringLength(220)]
    public string Composer { get; set; }

<<<<<<<< HEAD:Musica/Models/Track.cs
========
    [Required(ErrorMessage = "Campo olbitario.")]
    [DisplayName("Duración")]
>>>>>>>> f06e521 (Commit):IzquierdoAndres_Musica_Identity/Models/Track.cs
    public int Milliseconds { get; set; }

    public int? Bytes { get; set; }

    [Required(ErrorMessage = "Campo olbitario.")]
    [Column(TypeName = "numeric(10, 2)")]
    public decimal UnitPrice { get; set; }

    [ForeignKey("AlbumId")]
    [InverseProperty("Tracks")]
    public virtual Album Album { get; set; }

    [InverseProperty("Track")]
    public virtual ICollection<InvoiceLine> InvoiceLines { get; set; } = new List<InvoiceLine>();

    [InverseProperty("Track")]
    public virtual ICollection<PlaylistTrack> PlaylistTracks { get; set; } = new List<PlaylistTrack>();
}