// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Musica.Models;

namespace Musica.Data;

public partial class ChinookContext : DbContext
{
    public ChinookContext(DbContextOptions<ChinookContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Album> Albums { get; set; }

    public virtual DbSet<Artist> Artists { get; set; }

    public virtual DbSet<InvoiceLine> InvoiceLines { get; set; }

    public virtual DbSet<PlaylistTrack> PlaylistTracks { get; set; }

    public virtual DbSet<Track> Tracks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Album>(entity =>
        {
            entity.Property(e => e.AlbumId).ValueGeneratedNever();

            entity.HasOne(d => d.Artist).WithMany(p => p.Albums)
<<<<<<<< HEAD:Musica/Data/ChinookContext.cs
                .OnDelete(DeleteBehavior.ClientSetNull)
========
                .OnDelete(DeleteBehavior.ClientCascade)
>>>>>>>> f06e521 (Commit):IzquierdoAndres_Musica_Identity/Data/LocalDBChinookContext.cs
                .HasConstraintName("FK_AlbumArtistId");
        });

        modelBuilder.Entity<Artist>(entity =>
        {
            entity.Property(e => e.ArtistId).ValueGeneratedNever();
        });

        modelBuilder.Entity<InvoiceLine>(entity =>
        {
            entity.Property(e => e.InvoiceLineId).ValueGeneratedNever();

            entity.HasOne(d => d.Track).WithMany(p => p.InvoiceLines)
                .OnDelete(DeleteBehavior.ClientCascade)
                .HasConstraintName("FK_InvoiceLineTrackId");
        });

        modelBuilder.Entity<PlaylistTrack>(entity =>
        {
            entity.HasKey(e => new { e.PlaylistId, e.TrackId }).IsClustered(false);

            entity.HasOne(d => d.Track).WithMany(p => p.PlaylistTracks)
                .OnDelete(DeleteBehavior.ClientCascade)
                .HasConstraintName("FK_PlaylistTrackTrackId");
        });

        modelBuilder.Entity<Track>(entity =>
        {
            entity.Property(e => e.TrackId).ValueGeneratedNever();

<<<<<<<< HEAD:Musica/Data/ChinookContext.cs
            entity.HasOne(d => d.Album).WithMany(p => p.Tracks).HasConstraintName("FK_TrackAlbumId");
========
            entity.HasOne(d => d.Album).WithMany(p => p.Tracks)
            .OnDelete(DeleteBehavior.ClientCascade)
            .HasConstraintName("FK_TrackAlbumId");
>>>>>>>> f06e521 (Commit):IzquierdoAndres_Musica_Identity/Data/LocalDBChinookContext.cs
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    public DbSet<IzquierdoAndres_Musica.Models.Review>? Review { get; set; }
}