// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using UT03_Ej02_AndresIzquierdo.Data;

#nullable disable

namespace UT03_Ej02_AndresIzquierdo.Migrations
{
    //[DbContext(typeof(UT03_Ej02_AndresIzquierdoContext))]
    [Migration("20231120092338_GameGenreMig")]
    partial class GameGenreMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UT03_Ej02_AndresIzquierdo.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"), 1L, 1);

                    b.Property<int>("GenreIdGenre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("GameId");

                    b.HasIndex("GenreIdGenre");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("UT03_Ej02_AndresIzquierdo.Models.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenre"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("IdGenre");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("UT03_Ej02_AndresIzquierdo.Models.Game", b =>
                {
                    b.HasOne("UT03_Ej02_AndresIzquierdo.Models.Genre", "Genre")
                        .WithMany("GenreGames")
                        .HasForeignKey("GenreIdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("UT03_Ej02_AndresIzquierdo.Models.Genre", b =>
                {
                    b.Navigation("GenreGames");
                });
#pragma warning restore 612, 618
        }
    }
}
